### ISSUE TITLE
api-url not bound to env variable in slack.php

### ISSUE THREAD

**Issue by TrentBartlem** [OrthoLoess/jamyl-bot#13]

**Comment by prozn** [comment]
As this isn't environment specific or private information I'm not sure it needs to be in the .env file.

**Comment by TrentBartlem** [comment]
```
'api-url'   => 'https://provibloc.slack.com/api/'
```

It's not really appropriate for anyone else who uses it...

**Comment by OrthoLoess** [comment]
You're right that it will need to be different for other users, but so will several other config settings

I've not decided how to handle this yet, since I don't want to make the .env file too much of a mess with stuff that shouldn't really be in there.

**Comment by TrentBartlem** [comment]
Should be rolled into issue #14 ?
