### ISSUE TITLE
Channel management should be in database

### ISSUE THREAD

**Issue by TrentBartlem** [OrthoLoess/jamyl-bot#14]
slack.php implies it currently isn't.

**Comment by OrthoLoess** [comment]
You mean the channels-to-manage array?

If so, I agree. Will put it on the list.

**Comment by TrentBartlem** [comment]
- Mapping IDs to channel names
- which channels to manage
- which channels to auto-join
- what jamyl-id is set to (what is this, btw?) etc

**Comment by OrthoLoess** [comment]
Mapping of IDs to channel names is already in the database, the names in the config file are just comments to help remember which they are.

Channels to manage should go on there. Original plan was to have it just manage any channel it knew about, but I needed a way to limit it during testing. I now think it's better to have control.

Channels to auto-join: Unsure if this should go onto database, but I guess it could. Undecided.

jamyl-id is the ID of the slack user who is used for all the API functions. This has to be a real user (not a bot), has to have admin rights and has to be in all the private channels. This is far more appropriate as a config, as it is unlikely to change.

**Comment by TrentBartlem** [comment]
Fair enough. My goal for all open-source projects is that I should be able to clone the repo and configure it without touching a line of source code (database scripts are okay since I can make changes, execute the script then git reset)

**Comment by OrthoLoess** [comment]
I'd like to have it like that, I'm just not sure how best to achieve it. I feel that using the .env to such a great extent is not the way forward.

I guess one option would be to move the other stuff into it's own config file, that's not committed to git and include an install script that generates it with user input.

Thoughts?

**Comment by TrentBartlem** [comment]
Yeah that could work. It doesn't need to be an interactive script; just have the program exit with a helpful message if the config file doesn't exist or values are unset.

**Comment by TrentBartlem** [comment]
So, we're agreed?
