### ISSUE TITLE
API cron throws exception: in_array() expects paramter 2 to be array, null given.

### ISSUE THREAD

**Issue by Synthawk** [OrthoLoess/jamyl-bot#17]
Doing an exception trace found that it was failing on User.php:92

```
    if (in_array($this->alliance_id, config('standings.reds.alliances')) || in_array($this->corp_id, config('standings.reds.corporations'))) {
        $this->status = 'red';
        return true;
```

This is coming up because the reds group is not defined in standings.php (or the template file). Adding it in to the template fixes the problem. The issue only appeared to crop up during testing of the bot kicking members from Slack after leaving alliance, my assumption being because it goes through if statements and it no longer matched holder, blue or light-blue. Once it got to reds it would crash the entire API check because the group wasn't defined, but it has no issue with an empty group.

**Comment by OrthoLoess** [comment]
Sorry I kind of ignored this for so long. Your analysis is spot on. Fixed by PR #18
