### ISSUE TITLE
Slack renews admin token on logout/login(not really an jamyl-bot issue)

### ISSUE THREAD

**Issue by johanko** [OrthoLoess/jamyl-bot#19]
When I logout and login my user linked to the jamyl-bot it renews the admin token and auth errors follows. I guess there's no way around this?

I also have a question.
Tried contacting you ingame OrthoLoess, you quit playing?

I'm new to laravel, artisan and queues and tbh I don't know how I setup the queues. I can fire the jamyl: commands manually with artisan, but I would love to set them up in job queues. Queue driver is setup as default 'sync'. Anyone care to help me out?
Thanks.

**Comment by OrthoLoess** [comment]
Ortho Loess (with a space) I still play. Don't always respond to mails all that quickly.

Alas, nothing we can do about slack changing the admin token. I never log in the char I use for the access control stuff.

No queues in use currently. What you're looking for is Task Scheduling. See here: https://laravel.com/docs/5.2/scheduling

Short version is that you need a cron job that looks like this: 
`* * * * * php /path/to/artisan schedule:run >> /dev/null 2>&1`

**Comment by johanko** [comment]
Ahh, it's as easy as that :)
I need to put in one for every jamyl command?
EDIT: I go to fast, I found out about the schedule:run. My question is actually can I disable some of the jamyl:commands from the schedule until we set it up 100%?

**Comment by OrthoLoess** [comment]
You can comment them out in this file: https://github.com/OrthoLoess/jamyl-bot/blob/master/app/Console/Kernel.php

**Comment by johanko** [comment]
Thank you, and thanks for making this awesome stuff! Saves us alot of hassle.
