### ISSUE TITLE
Integrity contstraint on admin users

### ISSUE THREAD

**Issue by johanko** [OrthoLoess/jamyl-bot#20]
Have three admins and about 100 non admins, on allchecks I get this exception on the three admins, and cache errors follows(took out the id's):
`[2016-02-26 00:00:02] local.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-eve-CharacterAffiliation-;ids=<admin1>,<admin2>,<admin3>,10' for key 'PRIMARY'' in /home/evesso/jamyl-bot/vendor/3rdpartyeve/phealng/lib/Pheal/Cache/PdoStorage.php:265`
Any ideas? Yell at me if you need additional info.

**Comment by OrthoLoess** [comment]
The problem appears to be occurring in Pheal's cache. It's trying to write in something that's already in the cache and it's failing because it doesn't allow duplicates. Presumably it was supposed to have deleted that entry before adding the new one but has not for some reason.

Less helpful suggestion: Use Redis.

Possibly more helpful if you can't or don't want to switch to redis: Flush the Pheal cache table from the DB and hope it was just a random bug that got that bit of data stuck in there.

**Comment by johanko** [comment]
I switched to redis caching and it's sorted, cheers.
Tought this was why some inactive users did not get disabled, but I still have about 60 users which should have been disabled on our slackteam. They are still lurking in the shadows in default general channel :P Any ideas why this is without having more info?

**Comment by OrthoLoess** [comment]
When you say inactive, do you mean that they are not playing at the moment but are still in a corp/alliance that has access or that they are no longer in a corp/alliance that has access?

**Comment by OrthoLoess** [comment]
The cache issue seems to indicate (as a side effect) that only those 3 characters were being checked on that call. Which seems odd. Maybe it's not checking anyone else for some reason.

Checkt eh time stamps in the database on the user table. There's a column where it says when to next check them. Could the server clock have got changed at some point?

**Comment by johanko** [comment]
All users been updated 08:30 and next update is 08:44. The 3 admins has the first 3 id's(1,2 and 4).
What seems to be our issue is jamyl-bot not disabling the users not registered in the jamyl-bot db. These are users manually invited before we added the jamyl-bot. I can now see one user who was in db and has quit corp, his slack user was correctly disabled.

**Comment by OrthoLoess** [comment]
Ah yes, you can add people who are already registered to jamyl, there's a couple of ways. (We had slack running before I wrote the bot)

If you can get them to do it themselves, they just need to register with the same email that they used for slack and it will link them automatically.

The way to do it for them used to involve just putting them in the db manually, but I got bored of that and made an artisan command for it. I think it takes their email and char id.

Edit: Command is jamyl:adduser - You can use `php artisan help jamyl:adduser` to get info on it.

**Comment by johanko** [comment]
ahh right, jamyl:register command, it seems to skip those inactive, but i'll just manually disable them.

Thanks for your guiding Ortho :)
