### ISSUE TITLE
BroadcastServiceProvider not found

### ISSUE THREAD

**Issue by jesterlol** [OrthoLoess/jamyl-bot#21]
composer install puts out this:
http://i.imgur.com/Suf5sQ2.png

**Comment by OrthoLoess** [comment]
This is... odd.

master branch is what I am currently running, so either something has changed upstream, or something is odd on your end

**Comment by jesterlol** [comment]
I forked the repo, made the changes (almost all of them) in the config files, committed and then put everything on my server.

I used the windows app for github and this might have fucked up something. It's the only thing I could imagine, because after I deleted everything, then manually downloaded the .zip and extracted it on the server, it was no problem running "composer install".

**Comment by OrthoLoess** [comment]
Looks like this was a one time, since no one else has reported similar, so will close
