### ISSUE TITLE
Users get slack_name slackbot

### ISSUE THREAD

**Issue by johanko** [OrthoLoess/jamyl-bot#22]
Random users who registers gets the slack_name='slackbot' and slack_id='USLACKBOT'
This then errors and exits when trying to invite to the channel. As it exits, no new "good" users get's added before the error is fixed by manually altering the users row.

`[2016-04-01 06:50:03] local.ERROR: Exception thrown on USLACKBOT when adding to CHANNEL(edited)`
`[2016-04-01 06:50:03] local.ERROR: exception 'JamylBot\Exceptions\SlackException' with message 'cant_invite' in /SlackMonkey.php:140`

I would love to be more helpful and tell you why, but it beats me. Will have a closer look.

**Comment by OrthoLoess** [comment]
It seems that the slack API team added slackbot to the list of returned users for some reason. I've pushed a fix that basically jsut pops the last entry off the user list every time it is pulled. slackbot _seems_ to always be the last one, but I really ought to handle it a bit better. Works for now though.
