### ISSUE TITLE
zKillMonkey skipping kills

### ISSUE THREAD

**Issue by prozn** [OrthoLoess/jamyl-bot#26]
Currently zKillMonkey only requests kills after the last kill ID retrieved. It is possible, when kills are not added to the zkill database in chronological order, that a smaller kill ID will be added after a more recent kill. This can cause kills to be missed, with greater likelihood the shorter the zkill polling time is.

Possible fix: store all broadcasted kill IDs for a few hours and check versus that database whether the kill has already been broadcasted, rather than just checking if the kill ID is greater than the last broadcast.

**Comment by OrthoLoess** [comment]
killbot has now been rewritten and moved to its own repo
