### ISSUE TITLE
SlackException in SlackMonkey.php line 236: already_invited

### ISSUE THREAD

**Issue by jesterlol** [OrthoLoess/jamyl-bot#28]
When I delete a user from the "database" manually and then the user is trying to register again with the same e-mail adress he also used before I deleted him, he gets the error message in the title (see screenshot).

http://i.imgur.com/MeIZpPH.png

I understand that this is an issue because the mail adress was already invited once...but where can I find those entries and delete them if not in the slack database under user?

**Comment by jesterlol** [comment]
Ok, I see that this is more on the slack side of things.
If a user once registered with a maila dress, then leaves corp and you delete their account from slack.
You get the error message above if on one day that same person gets back into corp and tries to register again with the same mail adress.

But also I can not find this user under deactivated users or similar as it was deleted earlier when the user left the corp.

**Comment by OrthoLoess** [comment]
If you manually reenable the account on slack, it can be rebound by using the /register command

**Comment by jesterlol** [comment]
yeah I already thought something like that.
The problem is that they are not on the slack member list anymore, so I can not re-enable them.

Is there a way to manually add someone without using the "normal" slack invite...so that they are actually being checked by the bot? (how does jamyl:adduser work?)

---

for now I just used jamyl:adduser, then invited them via slack manually and then they used "/register" and it says that say are registered now. They also show up in the database, etc. Does this work in terms of if I remove them from the database or they leave corp that they are getting deactivated?
