### ISSUE TITLE
Issue with AFK access/corp that is red in blue alliance

### ISSUE THREAD

**Issue by gpatrouette** [OrthoLoess/jamyl-bot#32]
I am in the alliance Silent Infinity, and when I try to register at the instance [here](http://slack.provibloc.net/), I get this message:
> Welcome Guy Patrouette.
> You do not appear to have the correct standings on this character.
> Corp: Miners Of New Eden, Alliance: Silent Infinity
> If you have recently switched corps, then come back in an hour to see if the API has updated.
> If you think this corp/alliance should have access, contact Zenith Bane regarding the access list.

My alliance is blue to CVA, as I can use CVA jump bridges, and we are also a sov-holding alliance, so something is wrong here, but I am not sure if this is the right place to report this bug.

However, while checking out the code, I discovered an additional bug.  The standings checking code cannot handle the case where a corp in a blue alliance is red.  In [this function](https://github.com/OrthoLoess/jamyl-bot/blob/master/app/User.php#L78), the code returns True when an alliance is blue, without checking anything about the corp.  I think the fix for this should be simple: remove all but the last return statement (I'm not entirely sure what the `return True`s are doing, to be honest, it seems to always return True.  If the return value needs to be kept, you can have a temporary variable that stores the return value until the end of the function.).  If desired, I could try writing up a patch to fix this.

**Comment by OrthoLoess** [comment]
the "red" standings are not used by our install so I don't really worry about it. the return statements are explicitly designed to halt execution at that point and avoid having to run the rest of the function.

Your way of doing it would cause the last rule to take precedence, the original way causes the first to take precedence.

I can see the value of having "red" come first, and would probably accept a PR that did this

The return values are indeed not used.

**Comment by OrthoLoess** [comment]
As for the standings issue, this is not the place.

**Comment by gpatrouette** [comment]
Yep, I did not notice that bug in my fix.  I guess I should have tried to test it.  Anyways, this is no longer a problem for me, as I have moved alliances, so I probably won't end up trying to write up a fix.
